version: '3'
services:
  web:
    build: ../app-code
    image: future-flask-redis:latest
    ports:
      - 5000
  redis:
    image: redis:alpine
  nginx:
    image: nginx:latest
    ports:
        - 80:80
    volumes:
        - './nginx/nginx.conf:/etc/nginx/nginx.conf'
